[package]
name = "pi_motor_control"
version = "0.1.0"
authors = ["michael"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = { version = "0.12.0", features = ["hal"] }
log = "0.4"
